### ISSUE TITLE
Errors in hotspot csv data

### ISSUE THREAD

**Issue by manojkmohan** [CODD-K/covid19kerala.info-data#1]
When i was checking the hotspot data in released dataset, found some unwanted rows. Notified, Nikhil too. 
![Screenshot from 2020-07-19 23-51-17](https://user-images.githubusercontent.com/452426/87882444-aa679980-ca1d-11ea-8075-3f588f8fbc2c.png)

**Comment by nishad** [comment]
@manojkmohan Released an update `v3.1.1` for `v3.1.0` with https://github.com/CODD-K/covid19kerala.info-data/commit/cd8c1db6e0c041e410430f59463ca37e4ebd5475. Thank you for reporting this.
